In [1]:
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data_folder = f"../data"

sample_filename = "muestreos_parcelas.parquet"

df_samples = pd.read_parquet(f"{data_folder}/{sample_filename}")

df_samples["fecha"] = pd.to_datetime(df_samples["fecha"])


df_samples["codparcela"] = df_samples["codparcela"].str.replace("/", "")

df_samples.info()

<class 'pandas.core.frame.DataFrame'>
Index: 581793 entries, 0 to 581792
Data columns (total 61 columns):
 #   Column                                              Non-Null Count   Dtype
---  ------                                              --------------   -----
 0   generated_muestreos                                 581793 non-null  datetime64[us]
 1   codparcela                                          581793 non-null  object
 2   provincia                                           581793 non-null  string
 3   municipio                                           581793 non-null  string
 4   fecha                                               581793 non-null  datetime64[us]
 5   campaña                                             581793 non-null  uint16
 6   poligono                                            581731 non-null  UInt16
 7   parcela                                             581763 non-null  UInt16
 8   recinto                                             580067 non-null  UInt8
 9   subrecinto                                          477220 non-null  Int8
 10  estado_fenologico_1                                 35816 non-null   float32
 11  estado_fenologico_2                                 62000 non-null   float32
 12  estado_fenologico_3                                 56106 non-null   float32
 13  estado_fenologico_4                                 43386 non-null   float32
 14  estado_fenologico_5                                 37543 non-null   float32
 15  estado_fenologico_6                                 40460 non-null   float32
 16  estado_fenologico_7                                 43052 non-null   float32
 17  estado_fenologico_8                                 43815 non-null   float32
 18  estado_fenologico_9                                 109202 non-null  float32
 19  estado_fenologico_10                                243629 non-null  float32
 20  estado_fenologico_11                                99547 non-null   float32
 21  estado_fenologico_12                                70410 non-null   float32
 22  estado_fenologico_13                                33154 non-null   float32
 23  estado_fenologico_14                                7441 non-null    float32
 24  porcentaje_floracion                                28589 non-null   float32
 25  generated_parcelas                                  578353 non-null  datetime64[us]
 26  102_coordenada_x_(utm)                              570857 non-null  float64
 27  103_coordenada_y_(utm)                              570759 non-null  float64
 28  104_altitud_(m)                                     389024 non-null  float32
 29  105_comarca                                         577883 non-null  category
 30  201_superf_cultivada_en_la_parcela_agrícola_(ha)    530584 non-null  float32
 31  202_pendiente_(%)                                   380385 non-null  float32
 32  203_orientación                                     244094 non-null  category
 33  204_textura_del_suelo                               263146 non-null  category
 34  206_secano_/_regadío                                512875 non-null  category
 35  211_utilización_de_cubierta_vegetal                 420356 non-null  category
 36  212_tipo_de_cubierta_vegetal                        253266 non-null  category
 37  214_cultivo_asociado/otro_aprovechamiento           62273 non-null   category
 38  301_marco_(m_x_m)                                   498433 non-null  category
 39  302_densidad_(plantas/ha)                           500483 non-null  float32
 40  303_nº_pies_por_árbol                               443244 non-null  float32
 41  304_formación                                       155534 non-null  category
 42  305_diámetro_de_copa_(m)                            122053 non-null  float32
 43  308_variedad_principal                              523792 non-null  category
 44  311_fecha_de_plantación_variedad_principal          144847 non-null  category
 45  208_riego:_procedencia_del_agua                     139171 non-null  category
 46  209_riego:_calidad_del_agua                         119292 non-null  category
 47  313_variedad_secundaria                             89462 non-null   category
 48  107_zona_homogénea                                  357065 non-null  category
 49  120_zona_biológica_raif                             573062 non-null  category
 50  401_estación_climática_asociada                     410768 non-null  category
 51  402_sensor_climático_asociado                       168841 non-null  category
 52  207_riego:_sistema_usual_de_riego                   183943 non-null  category
 53  108_u_h_c_a_la_que_pertenece                        308923 non-null  category
 54  316_fecha_de_plantación_variedad_secundaria         22115 non-null   category
 55  315_patrón_variedad_secundaria                      18428 non-null   category
 56  317_%_superficie_ocupada_variedad_secundaria        23241 non-null   float32
 57  306_altura_de_copa_(m)                              72260 non-null   float64
 58  310_patrón_variedad_principal                       135256 non-null  category
 59  411_representa_a_la_u_h_c_(si/no)                   192345 non-null  category
 60  109_sistema_para_el_cumplimiento_gestión_integrada  148302 non-null  category
dtypes: Int8(1), UInt16(2), UInt8(1), category(25), datetime64[us](3), float32(22), float64(3), object(1), string(2), uint16(1)
memory usage: 117.3+ MB

In [5]:
parcela_filename = "parcelas_download.txt"
df_parcelas = pd.read_csv(f"{data_folder}/{parcela_filename}", sep="\t", usecols=["codparcela", "lat", "lon", "fecha_primera_muestra", "fecha_ultima_muestra"])
df_parcelas.head()

,codparcela,fecha_primera_muestra,fecha_ultima_muestra,lat,lon
0,015-00002-00-00,2006-03-08,2021-03-16,37.802069,-3.984598
1,043-00008-00-00,2006-04-10,2017-11-13,36.944813,-5.301941
2,017-00204-00-00,2006-05-10,2019-09-03,38.052148,-3.312451
3,010-00016-00-00,2006-03-06,2017-07-18,38.070431,-3.509408
4,007-00018-01-01,2010-03-08,2021-03-24,38.043972,-4.463010

In [25]:
#df_samples  = pd.merge(df_samples, df_parcelas, on='codparcela', how='left')
df_samples.head()

,generated_muestreos,codparcela,provincia,municipio,fecha,campaña,poligono,parcela,recinto,subrecinto,...,402_sensor_climático_asociado,207_riego:_sistema_usual_de_riego,108_u_h_c_a_la_que_pertenece,316_fecha_de_plantación_variedad_secundaria,315_patrón_variedad_secundaria,317_%_superficie_ocupada_variedad_secundaria,306_altura_de_copa_(m),310_patrón_variedad_principal,411_representa_a_la_u_h_c_(si/no),109_sistema_para_el_cumplimiento_gestión_integrada
0,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-04-16,2006,23,109,0,0,...,AL006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-04-27,2006,23,109,0,0,...,AL006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-05-04,2006,23,109,0,0,...,AL006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-05-11,2006,23,109,0,0,...,AL006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-05-17,2006,23,109,0,0,...,AL006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
parcelas_with_data = [file.split("_BIOPAR")[0] for file in os.listdir("../data/raw/NVDI_FAPAR_data") if "NDVI" in file]

df_samples = df_samples[df_samples["codparcela"].isin(parcelas_with_data)]

In [61]:
df_samples.to_parquet("../data/subset_muestreos_parcelas.parquet")

In [8]:
raw_data_folder = f"../data/raw"
parcelas_with_data = [file.split("_BIOPAR")[0] for file in os.listdir(f"{raw_data_folder}/NVDI_FAPAR_data") if "NDVI" in file]


for id_parcela in parcelas_with_data:

    datos_parcela = [file for file in os.listdir(f"{raw_data_folder}/NVDI_FAPAR_data") if id_parcela in file]

    ndvi_filename = next((file for file in datos_parcela if "NDVI" in file), None)
    fapar_filename = next((file for file in datos_parcela if "FAPAR" in file), None)

    df_ndvi = pd.read_csv(f"{raw_data_folder}/NVDI_FAPAR_data/{ndvi_filename}", sep="\t", index_col=0)
    df_fapar = pd.read_csv(f"{raw_data_folder}/NVDI_FAPAR_data/{fapar_filename}", sep="\t", index_col=0)

    df_merge = pd.merge(df_ndvi, df_fapar, on='date', how='outer', suffixes=('_ndvi', '_fapar')).sort_values(by="date").reset_index(drop=True)

    df_merge.to_csv(f"../data/clean/NVDI_FAPAR_data/{id_parcela}.csv", sep="\t")

In [3]:
from zipfile import ZipFile
data_folder = f"../data/raw/other_variables_data"
unzip_data_folder = f"../data/clean/other_variables_data"

raw_files = os.listdir(data_folder)
nc_filename = "data.nc"

for raw_file in raw_files:
    filename = raw_file.split(".")[0]
    try:
        with ZipFile(f"{data_folder}/{raw_file}") as zip_object:
            zip_object.extractall(path=unzip_data_folder)

        os.rename(f"{unzip_data_folder}/{nc_filename}", f"{unzip_data_folder}/{filename}.nc")
    except:
        print(raw_file)

In [8]:

import os
unzip_data_folder = f"../data/clean/other_variables_data"

nc_files = os.listdir(unzip_data_folder)

In [9]:
unzip_data_folder

'../data/clean/other_variables_data'

In [2]:
import xarray as xr

# file_pattern = f"{unzip_data_folder}/METEO_DATA_*.nc"

# ds = xr.open_mfdataset(file_pattern, combine='by_coords', chunks={'time': 'auto'})


# Print the combined dataset

# Save the combined dataset to a new NetCDF file

#ds.to_netcdf("path/to/output/combined_data.nc")

In [11]:
ds.to_netcdf("../data/clean/combined_other_variables.nc")

In [3]:

ds = xr.open_dataset("../data/clean/combined_other_variables.nc")

In [83]:
df_parcelas = df_parcelas[df_parcelas.index>=3142]

In [86]:
df_parcelas

,codparcela,fecha_primera_muestra,fecha_ultima_muestra,lat,lon
3142,115-00087-00-/2,2006-04-11,2007-11-26,3.676176e+01,-6.004775e+00
3143,001-00006-00-00,2006-03-22,2006-11-21,3.750902e+01,-4.570450e+00
3144,008-00172-01-00,2013-03-26,2014-11-05,3.800243e+01,-3.568166e+00
3145,004-00212-00-00,2006-04-03,2007-11-12,3.746040e+01,-4.255956e+00
3146,018-00233-00-00,2006-04-11,2007-11-12,3.805630e+01,-3.319798e+00
...,...,...,...,...,...
5234,007-00086-01-01,2019-03-20,2019-03-20,3.731774e+01,-4.842136e+00
5235,035-00035-03-00,2021-03-11,2021-03-11,3.744146e+01,-4.647516e+00
5236,119-00019-00-A0,2008-10-27,2008-10-27,-9.999999e+06,-9.999999e+06
5237,035-00037-02-1,2021-03-15,2021-03-15,3.733449e+01,-3.860952e+00
5238,028-00007-08,2021-02-03,2021-02-03,-9.999999e+06,-9.999999e+06

In [6]:
for _, row in df_parcelas.iterrows():
    id_parcela = row["codparcela"].replace("/", "")

    start_time = row["fecha_primera_muestra"]
    end_time = row["fecha_ultima_muestra"]
    latitude_parcela = row["lat"]
    longitude_parcela = row["lon"]

    ds_parcela = ds.sel(time=slice(start_time, end_time))
    ds_parcela = ds_parcela.interp(latitude=latitude_parcela, longitude=longitude_parcela)

    df_data_parcela = ds_parcela.to_pandas()

    df_data_parcela.to_csv(f"../data/clean/other_variables_data_dfs/{id_parcela}.csv", sep="\t")

In [3]:
fapar_folder = "../data/clean/NVDI_FAPAR_data"
other_files_folder = "../data/clean/other_variables_data_dfs"
final_data_folder = "../data/clean/final"

fapar_files = os.listdir(fapar_folder)
other_files = os.listdir(other_files_folder)

In [4]:
for fapar_file in fapar_files:

    filename = fapar_file.split(".csv")[0]

    df_fapar = pd.read_csv(f"{fapar_folder}/{fapar_file}", sep="\t", index_col=0, parse_dates=["date"])

    df_other_files = pd.read_csv(f"{other_files_folder}/{fapar_file}", sep="\t", index_col=0, parse_dates=["time"]).reset_index()

    df_other_files.rename(columns={"time":"date"}, inplace=True)

    df_final_data = pd.merge(df_fapar, df_other_files, on="date", how="outer").sort_values(by="date").reset_index(drop=True)


    df_final_data.to_csv(f"{final_data_folder}/{fapar_file}", sep="\t")