In [35]:
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [36]:
data_folder = f"../data"

sample_filename = "muestreos_parcelas.parquet"

df_samples = pd.read_parquet(f"{data_folder}/{sample_filename}")

df_samples["fecha"] = pd.to_datetime(df_samples["fecha"])


df_samples["codparcela"] = df_samples["codparcela"].str.replace("/", "")

df_samples.info()

<class 'pandas.core.frame.DataFrame'>
Index: 581793 entries, 0 to 581792
Data columns (total 61 columns):
 #   Column                                              Non-Null Count   Dtype
---  ------                                              --------------   -----
 0   generated_muestreos                                 581793 non-null  datetime64[us]
 1   codparcela                                          581793 non-null  object
 2   provincia                                           581793 non-null  string
 3   municipio                                           581793 non-null  string
 4   fecha                                               581793 non-null  datetime64[us]
 5   campaña                                             581793 non-null  uint16
 6   poligono                                            581731 non-null  UInt16
 7   parcela                                             581763 non-null  UInt16
 8   recinto                                             580067 non-null  UInt8
 9   subrecinto                                          477220 non-null  Int8
 10  estado_fenologico_1                                 35816 non-null   float32
 11  estado_fenologico_2                                 62000 non-null   float32
 12  estado_fenologico_3                                 56106 non-null   float32
 13  estado_fenologico_4                                 43386 non-null   float32
 14  estado_fenologico_5                                 37543 non-null   float32
 15  estado_fenologico_6                                 40460 non-null   float32
 16  estado_fenologico_7                                 43052 non-null   float32
 17  estado_fenologico_8                                 43815 non-null   float32
 18  estado_fenologico_9                                 109202 non-null  float32
 19  estado_fenologico_10                                243629 non-null  float32
 20  estado_fenologico_11                                99547 non-null   float32
 21  estado_fenologico_12                                70410 non-null   float32
 22  estado_fenologico_13                                33154 non-null   float32
 23  estado_fenologico_14                                7441 non-null    float32
 24  porcentaje_floracion                                28589 non-null   float32
 25  generated_parcelas                                  578353 non-null  datetime64[us]
 26  102_coordenada_x_(utm)                              570857 non-null  float64
 27  103_coordenada_y_(utm)                              570759 non-null  float64
 28  104_altitud_(m)                                     389024 non-null  float32
 29  105_comarca                                         577883 non-null  category
 30  201_superf_cultivada_en_la_parcela_agrícola_(ha)    530584 non-null  float32
 31  202_pendiente_(%)                                   380385 non-null  float32
 32  203_orientación                                     244094 non-null  category
 33  204_textura_del_suelo                               263146 non-null  category
 34  206_secano_/_regadío                                512875 non-null  category
 35  211_utilización_de_cubierta_vegetal                 420356 non-null  category
 36  212_tipo_de_cubierta_vegetal                        253266 non-null  category
 37  214_cultivo_asociado/otro_aprovechamiento           62273 non-null   category
 38  301_marco_(m_x_m)                                   498433 non-null  category
 39  302_densidad_(plantas/ha)                           500483 non-null  float32
 40  303_nº_pies_por_árbol                               443244 non-null  float32
 41  304_formación                                       155534 non-null  category
 42  305_diámetro_de_copa_(m)                            122053 non-null  float32
 43  308_variedad_principal                              523792 non-null  category
 44  311_fecha_de_plantación_variedad_principal          144847 non-null  category
 45  208_riego:_procedencia_del_agua                     139171 non-null  category
 46  209_riego:_calidad_del_agua                         119292 non-null  category
 47  313_variedad_secundaria                             89462 non-null   category
 48  107_zona_homogénea                                  357065 non-null  category
 49  120_zona_biológica_raif                             573062 non-null  category
 50  401_estación_climática_asociada                     410768 non-null  category
 51  402_sensor_climático_asociado                       168841 non-null  category
 52  207_riego:_sistema_usual_de_riego                   183943 non-null  category
 53  108_u_h_c_a_la_que_pertenece                        308923 non-null  category
 54  316_fecha_de_plantación_variedad_secundaria         22115 non-null   category
 55  315_patrón_variedad_secundaria                      18428 non-null   category
 56  317_%_superficie_ocupada_variedad_secundaria        23241 non-null   float32
 57  306_altura_de_copa_(m)                              72260 non-null   float64
 58  310_patrón_variedad_principal                       135256 non-null  category
 59  411_representa_a_la_u_h_c_(si/no)                   192345 non-null  category
 60  109_sistema_para_el_cumplimiento_gestión_integrada  148302 non-null  category
dtypes: Int8(1), UInt16(2), UInt8(1), category(25), datetime64[us](3), float32(22), float64(3), object(1), string(2), uint16(1)
memory usage: 117.3+ MB

In [37]:
parcela_filename = "parcelas_download.txt"
df_parcelas = pd.read_csv(f"{data_folder}/{parcela_filename}", sep="\t", index_col=0, usecols=["codparcela", "lat", "lon"])
df_parcelas.head()

                       lat       lon
codparcela
015-00002-00-00  37.802069 -3.984598
043-00008-00-00  36.944813 -5.301941
017-00204-00-00  38.052148 -3.312451
010-00016-00-00  38.070431 -3.509408
007-00018-01-01  38.043972 -4.463010

In [42]:
#df_samples  = pd.merge(df_samples, df_parcelas, on='codparcela', how='left')
df_samples.head()

,generated_muestreos,codparcela,provincia,municipio,fecha,campaña,poligono,parcela,recinto,subrecinto,...,108_u_h_c_a_la_que_pertenece,316_fecha_de_plantación_variedad_secundaria,315_patrón_variedad_secundaria,317_%_superficie_ocupada_variedad_secundaria,306_altura_de_copa_(m),310_patrón_variedad_principal,411_representa_a_la_u_h_c_(si/no),109_sistema_para_el_cumplimiento_gestión_integrada,lat,lon
0,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-04-16,2006,23,109,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.146121,-2.769372
1,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-04-27,2006,23,109,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.146121,-2.769372
2,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-05-04,2006,23,109,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.146121,-2.769372
3,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-05-11,2006,23,109,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.146121,-2.769372
4,2020-04-23 14:30:39,023-00109-00-00,almeria,abla,2006-05-17,2006,23,109,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.146121,-2.769372

In [57]:
parcelas_with_data = [file.split("_BIOPAR")[0] for file in os.listdir("../data/raw/NVDI_FAPAR_data") if "NDVI" in file]

df_samples = df_samples[df_samples["codparcela"].isin(parcelas_with_data)]

In [61]:
df_samples.to_parquet("../data/subset_muestreos_parcelas.parquet")

In [108]:
parcelas_with_data = [file.split("_BIOPAR")[0] for file in os.listdir("../data/raw/NVDI_FAPAR_data") if "NDVI" in file]

for id_parcela in parcelas_with_data:

    datos_parcela = [file for file in os.listdir("../data/NVDI_FAPAR_data") if id_parcela in file]

    ndvi_filename = next((file for file in datos_parcela if "NDVI" in file), None)
    fapar_filename = next((file for file in datos_parcela if "FAPAR" in file), None)

    df_ndvi = pd.read_csv(f"../data/NVDI_FAPAR_data/{ndvi_filename}", sep="\t", index_col=0)
    df_fapar = pd.read_csv(f"../data/NVDI_FAPAR_data/{fapar_filename}", sep="\t", index_col=0)

    df_merge = pd.merge(df_ndvi, df_fapar, on='date', how='outer', suffixes=('_ndvi', '_fapar')).sort_values(by="date").reset_index(drop=True)

    df_merge.to_csv(f"../data/clean/NVDI_FAPAR_data/{id_parcela}.csv", sep="\t")